version: '3.8'

services:
  # PostgreSQL optimized for mobile GPS tracking data
  postgres:
    image: postgres:18
    container_name: fleettracker-postgres
    environment:
      POSTGRES_DB: fleettracker
      POSTGRES_USER: fleettracker
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init-timescale.sql:/docker-entrypoint-initdb.d/init-timescale.sql
    networks:
      - fleettracker-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fleettracker -d fleettracker"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: fleettracker-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fleettracker-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

  # Backend API (for development)
  backend:
    build: .
    container_name: fleettracker-backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://fleettracker:password123@postgres:5432/fleettracker?sslmode=disable
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-for-development
      PORT: 8080
      ENVIRONMENT: development
      DEBUG: true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - fleettracker-network
    volumes:
      - .:/app
      - /app/vendor
    working_dir: /app
    command: go run cmd/server/main.go

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fleettracker-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fleettracker.id
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - fleettracker-network
    depends_on:
      - postgres

  # Redis Commander for Redis management (optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: fleettracker-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - fleettracker-network
    depends_on:
      - redis

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  fleettracker-network:
    driver: bridge
